-- Create admin users table
create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  name text,
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.admin_users enable row level security;

-- Create policies for admin users
drop policy if exists "Allow admin login" on public.admin_users;
create policy "Allow admin login"
on public.admin_users
for select
to anon, authenticated
using (true);

-- Insert your admin user (replace with your actual credentials)
-- IMPORTANT: Replace 'your-email@example.com' and 'your-secure-password'
insert into public.admin_users (email, password_hash, name) 
values (
  'your-email@example.com', 
  'your-secure-password-hash', -- You should hash this properly
  'Admin User'
)
on conflict (email) do update set
  password_hash = excluded.password_hash,
  name = excluded.name;
