create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null,
  customer_email text not null,
  total numeric not null,
  order_date text not null,
  impact_kg numeric default 3.2,
  created_at timestamptz default now()
);

alter table public.orders enable row level security;

drop policy if exists "Allow anon insert orders" on public.orders;
create policy "Allow anon insert orders"
on public.orders
for insert
to anon, authenticated
with check (true);

create table if not exists public.community_feedback (
  id bigint generated by default as identity primary key,
  product_id text not null,
  product_name text not null,
  rating int not null,
  vote_type text not null,
  comment text not null,
  author_email text not null,
  created_at_text text not null,
  created_at timestamptz default now()
);

alter table public.community_feedback enable row level security;

drop policy if exists "Allow anon insert feedback" on public.community_feedback;
create policy "Allow anon insert feedback"
on public.community_feedback
for insert
to anon, authenticated
with check (true);

drop policy if exists "Allow anon read feedback" on public.community_feedback;
create policy "Allow anon read feedback"
on public.community_feedback
for select
to anon, authenticated
using (true);
