-- Create users table for customer registrations
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz default now()
);

-- Enable RLS (Row Level Security)
alter table public.users enable row level security;

-- Create policies for users table
drop policy if exists "Allow insert for registration" on public.users;
create policy "Allow insert for registration"
on public.users
for insert
to anon, authenticated
with check (true);

drop policy if exists "Allow select for all" on public.users;
create policy "Allow select for all"
on public.users
for select
to anon, authenticated
using (true);

-- Create index for faster email lookups
create index if not exists users_email_idx on public.users(email);
